### ISSUE TITLE
Include a call to rscript from a bash script

### ISSUE THREAD

**Issue by pappewaio** [KajsaGeorgii/Introduction#4]
It would be cool if your bash script calls R directly so you don't have to do this as a manual step.

Call an Rscript like this

```
Rscript script.R
```

Call an Rscript using arguments, for example input files or other parameters

```
Rscript script.R "inputfilename1" "othervar1" "othervar2"
```
Within the R script itself you catch the arguments by adding this line in top of you R script.

```
args = commandArgs(trailingOnly=TRUE)
# access as for a normal vector
filename <- args[1]
othervar1 <- args[2]
othervar2 <- args[3]

```

You could use this way of calling for your histogram script you already have.

**Comment by KajsaGeorgii** [comment]
All done :)

**Comment by pappewaio** [comment]
Good!
I can see that you have implemented the correct R code
https://github.com/KajsaGeorgii/Introduction/blob/5293d3a608af97e034514cec0d8d721bf52f3204/histogram.R#L1-L6

But where are you calling this script from? I cannot see Rscript being called from neither script.sh nor script2.sh.

The idea is to finally have only one main script to execute, which in turn starts other scripts :)

**Comment by pappewaio** [comment]
looks good!
