### ISSUE TITLE
Parallellization in bash

### ISSUE THREAD

**Issue by pappewaio** [KajsaGeorgii/Introduction#6]
To prepare ourselves for the arrival of the new computer with 10+ cores we can look into how to do parallellisation using bash. That is very useful, and is something I do a lot. My personal cutoff is when something takes more than a minute to run.

The way to do parallelisation in bash is to use the ampersand "&", which makes it easy to both understand for others and also see how to use it.
```
function funnyFunction(){
  sleep ${1}
  echo "slept ${1} sec"
}

arr=(2 4 7)
for i in ${arr[@]}; do
    funnyFunction $i &
done
wait
echo "all done"
```
See this guide for more examples and details:
https://twpower.github.io/188-run-multi-processes-in-shell-script-using-ampersand-en

When you start to work on a high performance cluster HPC, then there is also another command for parallellisation (as you share thousands of cores with other users), but it will follow the same thought pattern, which is:

1. Split the data in as equal portions as possible. Equal sizes are important to get the parallell jobs to finish at the same time. And that is important as we don't want to finish 9 out of 10 jobs in 10 seconds and then wait for the last one for a minute.
2. Split the data so that we can easily join the data later, but we can also continue to process the data chunks many times in parallell until we need to merge the them at a later stage.
3. Split the data in respect to what you need to perform a certain algorithm. If it is a rowbased algorithm, it is perfectly fine to split in any number of parallell processes, but let's say that you need information about the whole dataset for each row (typical for some matrix operations), then you might want to split into the sizes these matrix operations need. Although, this will be obvious when it happens, and is usually not that frequent when working in bash where everything is sort of made to be processed row by row, providing us with the great advantage of reducing internal memory usage and split the data as many times as we prefer (usually the max amount of cores the computer has).
4. When collecting the data at a processing step, remember to use the ```wait``` command to let your three parallell processes finish before you do for example cat file1 file2 file3 > files.txt to combine the results.
5. Manage intermediate files created along the pipeline. I.e., create a folder for each process/operation and store each intermediate chunk there with a name that can be used to assemble the chunks in the correct order. The correct order is usually needed, so good to always prepare for that. And make it easy to remove the intermediate folders ones you have confirmed that the output is as expected. We don't want to keep intermediate files as they usually take a lot of space, but they are extremely useful for debugging if anything goes wrong.
x. If I forgot to add anything here, we add it later.

So, the task is now to apply this to the gwas example data: split, perform some operations of your own choice, collect, and write a summary.

**Comment by KajsaGeorgii** [comment]
Återkommer när jag är färdig :) tack för uppgiften!

**Comment by pappewaio** [comment]
Super! Jag har kollat på det senaste du gjort och du har lyckats parallellisera ett job :)

Just nu gör du ju exakt samma sak två gånger, men skriver till två olika filer. Nästa steg skulle kunna vara att dela upp gwasfilens 10000 rader i 2 delar med 5000 rader var och processa dem var för sig.

**Comment by KajsaGeorgii** [comment]
Aha! Okej, har ändrat den nu. Tror det ska vara rätt den här gången :)

**Comment by pappewaio** [comment]
There is this pipeline manager, which can help with a lot of these things.
https://www.nextflow.io/

**Comment by pappewaio** [comment]
It seems we have completed this issue a while ago :)
